#!/bin/sh

list() {
	for f in *.vim; do
		printf '    %-15s %s \n' \
			"${f%%.*}" \
			"$(grep 'jumpy#map' "$f" | sed -E 's/call jumpy#map\(['"'"'"](.*)['"'"'"], [01]\)/\1/')"
	done
}

(cd ftplugin && list)
(cd after/ftplugin && list)
