#!/bin/sh

fmt='    %-12s %-35s %s\n'

list() {
	for f in *.vim; do
		desc=$(head -n1 "$f" | sed 's/^" //')
		printf "$fmt" \
			"${f%%.*}" \
			"$desc" \
			"$(grep 'jumpy#map' "$f" | sed -E 's/call jumpy#map\(['"'"'"](.*)['"'"'"]\)/\1/')"
	done
}

printf "$fmt" 'Filetype' 'What it matches' 'Regexp'
printf "$fmt" '--------' '---------------' '------'

(cd after/ftplugin && list)
